# Generated by Django 5.1.4 on 2024-12-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ("value_unique", models.CharField(max_length=32, unique=True)),
                ("value_unique_together_1", models.CharField(max_length=32)),
                ("value_unique_together_2", models.CharField(max_length=32)),
                ("value_not_null", models.CharField(max_length=32)),
            ],
            options={
                "unique_together": {("value_unique_together_1", "value_unique_together_2")},
            },
        ),
    ]
