# Generated by Django 5.1.4 on 2025-01-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="value_check",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(condition=models.Q(("value_check__gte", 0)), name="value_check_gte_0"),
        ),
    ]
