# Generated by Django 5.1.4 on 2025-01-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_resource_value_check_resource_value_check_gte_0"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildModel",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="children", to="api.resource"
                    ),
                ),
            ],
        ),
    ]
