name: Testing

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_USER: demo
          POSTGRES_PASSWORD: demo
          POSTGRES_DB: demo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.13'
      
      # UV
      - uses: yezz123/setup-uv@v4

      # Install dependencies
      - run: uv sync   
      
      # Imports
      - run: source .venv/bin/activate && pytest